// src/data/productData.ts
// Aggregates all per-category product JSON files generated by the migration script.

import type { Product } from '../types/product';
import { productAliases } from './productAliases';

// Import JSON files - Vite/Webpack supports importing .json directly.

import buttweld from './products/buttweld.json';
import fasteners from './products/fasteners.json';
import flanges from './products/flanges.json';
import forged from './products/forged.json';
import seamless from './products/seamless.json';
import reactangular from './products/reactangular.json';
import round from './products/round.json';
import sheets from './products/sheets.json';
import uncategorized from './products/uncategorized.json';

export const productData: Record<string, Product[]> = {
  'buttweld-fittings': buttweld as unknown as Product[],
  'fasteners': fasteners as unknown as Product[],
  'flanges': flanges as unknown as Product[],
  'forged-fittings': forged as unknown as Product[],
  'pipes-tubes': seamless as unknown as Product[],
  'hollow-sections': [...reactangular, ...uncategorized] as unknown as Product[],
  'round-bars': round as unknown as Product[],
  'wires': uncategorized as unknown as Product[],
  'sheets-coils': sheets as unknown as Product[],
};

export const findProductBySlug = (slug: string): Product | undefined => {
  // The slug in URL may include the category prefix, e.g. /products/pipes-tubes/ss-304-pipes-tubes
  // We'll split and look up within the appropriate category.
  const parts = slug.split('/');
  const productSlug = parts.pop() ?? '';
  const categorySlug = parts.pop() ?? '';
  const list = productData[categorySlug];
  if (!list) return undefined;
  return list.find((p) => p.slug === productSlug);
};

export const findProductByName = (categorySlug: string, name: string): Product | undefined => {
  let list = productData[categorySlug];
  if (!list) return undefined;

  // Use alias if it exists
  const searchName = productAliases[name] || name;

  const normalize = (s: string) => s.toLowerCase().replace(/stainless steel/g, 'ss').replace(/[^a-z0-9]/g, '');
  const normalizedTarget = normalize(searchName);

  return list.find((p) => normalize(p.title) === normalizedTarget);
};
