import type { DynamicCategory } from './productDetails'

/** Specialized / high-performance steel plates — separate from autogenerated productDetails.ts */
export const specializedCategory: DynamicCategory = {
  title: 'Specialized Products',
  slug: 'specialized-products',
  description: [
    'Vedantara Metal & Alloys is a leading manufacturer, exporter, and supplier of Specialized Steel Products in Mumbai, India. Our range includes Abrasion Resistant Plates, Corten Steel, Boiler Steel, Quenched & Tempered Steel, Armour Steel, Manganese Steel, and more — all manufactured to exacting international standards.',
    'These specialized steel products are engineered for extreme conditions — delivering superior hardness, wear resistance, impact strength, and structural integrity across mining, construction, shipbuilding, defense, earth-moving equipment, and pressure vessel fabrication.',
  ],
  subcategories: [
    {
      name: 'Abrasion Resistant Plates',
      image: '/images/products/abrasion-resistant-steel.jpg',
      productLinks: [
        { name: 'Abrasion Resistant Steel Plates', slug: 'abrasion-resistant-steel-plates' },
        { name: 'Abrex 400 Plates', slug: 'abrex-400-plates' },
        { name: 'Abrex 450 Plates', slug: 'abrex-450-plates' },
        { name: 'Abrex 500 Plates', slug: 'abrex-500-plates' },
        { name: 'Abrex 600 Plates', slug: 'abrex-600-plates' },
        { name: 'Rockstar 400 Plates', slug: 'rockstar-400-plates' },
        { name: 'Rockstar 450 Plates', slug: 'rockstar-450-plates' },
        { name: 'Rockstar 500 Plates', slug: 'rockstar-500-plates' },
        { name: 'AR 400 Plates', slug: 'ar-400-plates' },
        { name: 'AR 450 Plates', slug: 'ar-450-plates' },
        { name: 'AR 500 Plates', slug: 'ar-500-plates' },
        { name: 'AR 600 Plates', slug: 'ar-600-plates' },
        { name: 'JFE EH 360 / 400 / 500 Plates', slug: 'jfe-eh-360-400-500-plates' },
      ],
    },
    {
      name: 'Quenched & Tempered Steel',
      image: '/images/products/quenched-tempered-steel.jpg',
      productLinks: [
        { name: 'Quenched & Tempered Steel Plates', slug: 'quenched-tempered-steel-plates' },
        { name: 'S690ql Sheets & Plates', slug: 's690ql-sheets-plates' },
        { name: 'Weldox 700 Sheets & Plates', slug: 'weldox-700-sheets-plates' },
        { name: 'Welten 780E Sheets & Plates', slug: 'welten-780e-sheets-plates' },
        { name: 'JFE Hiten 780LE Sheets & Plates', slug: 'jfe-hiten-780le-sheets-plates' },
      ],
    },
    {
      name: 'Corten Steel',
      image: '/images/products/corten-steel-sheet.webp',
      productLinks: [
        { name: 'Corten Steel Plates', slug: 'corten-steel-plates' },
        { name: 'Corten Steel A Plates', slug: 'corten-steel-a-plates' },
        { name: 'Corten Steel B Plates', slug: 'corten-steel-b-plates' },
        { name: 'Corten Steel Gr A588 Plates', slug: 'corten-steel-gr-a588-plates' },
        { name: 'Corten Steel Gr 41 IRSM Plates', slug: 'corten-steel-gr-41-irsm-plates' },
      ],
    },
    {
      name: 'Boiler Steel',
      image: '/images/products/boiler-plate-steel.jpg',
      productLinks: [
        { name: 'Boiler Steel Plates', slug: 'boiler-steel-plates' },
        { name: 'ASTM A516 Grade 60 Steel Plates', slug: 'astm-a516-grade-60-steel-plates' },
        { name: 'ASTM A516 Grade 65 Steel Plates', slug: 'astm-a516-grade-65-steel-plates' },
        { name: 'ASTM A516 Grade 70 Steel Plates', slug: 'astm-a516-grade-70-steel-plates' },
        { name: 'NACE + HIC Resistant Steel Plates', slug: 'nace-hic-resistant-steel-plates' },
      ],
    },
    {
      name: 'Manganese Steel',
      image: '/images/products/manganese-steel-plate.avif',
      productLinks: [
        { name: 'Manganese Steel Plates', slug: 'manganese-steel-plates' },
        { name: '12 - 14% Manganese Plates', slug: '12-14-percent-manganese-plates' },
        { name: 'Hadfield Manganese Plates', slug: 'hadfield-manganese-plates' },
      ],
    },
    {
      name: 'Armour Steel',
      image: '/images/products/armour-steel-plate.jpg',
      productLinks: [
        { name: 'Armour Steel Plates', slug: 'armour-steel-plates' },
      ],
    },
    {
      name: 'DSQ Steel',
      image: '/images/products/dsq-steel-plate.webp',
      productLinks: [
        { name: 'DSQ Steel Plates', slug: 'dsq-steel-plates' },
      ],
    },
    {
      name: '15Mo3 & 16Mo3 Steel',
      image: '/images/products/15mo3-steel-plate.avif',
      productLinks: [
        { name: '15Mo3 Steel Plates', slug: '15mo3-steel-plates' },
        { name: '16Mo3 / SA 204 Steel Plates', slug: '16mo3-sa-204-steel-plates' },
      ],
    },
    {
      name: 'Tiscral Sailhard Plates',
      image: '/assets/products/tiscral-sailhard-plates-1.jpg',
      productLinks: [
        { name: 'Tiscral Sailhard Plates', slug: 'tiscral-sailhard-plates' },
      ],
    },
  ],
}
